# Generated by Django 5.2.7 on 2025-11-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='songs/images')),
                ('audio', models.FileField(upload_to='songs/audios')),
            ],
        ),
    ]
